# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('obs', models.CharField(blank=True, max_length=255, null=True)),
                ('dh_create', models.DateTimeField(auto_now_add=True)),
                ('dh_update', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('index', models.PositiveSmallIntegerField()),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('votes', models.PositiveIntegerField()),
                ('link', models.CharField(max_length=255)),
                ('user_create', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='imdbsurfer_movie_create_related', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='imdbsurfer_movie_update_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
