# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbsurfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
