# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbsurfer', '0002_auto_20170623_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='metascore',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='minutes',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
