# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbsurfer', '0005_moviegenre_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='index',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
