# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imdbsurfer', '0006_auto_20170708_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_create', models.DateTimeField(auto_now_add=True)),
                ('dh_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('obs', models.CharField(blank=True, max_length=255, null=True)),
                ('user_create', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='imdbsurfer_type_create_related', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='imdbsurfer_type_update_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='moviegenre',
            name='type',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='imdbsurfer.Type'),
            preserve_default=False,
        ),
    ]
