# Generated by Django 2.0.6 on 2018-06-13 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdbsurfer', '0008_auto_20170711_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='user_create',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_artist_create_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user_update',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_artist_update_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artistrole',
            name='user_create',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_artistrole_create_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artistrole',
            name='user_update',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_artistrole_update_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genre',
            name='user_create',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_genre_create_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genre',
            name='user_update',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_genre_update_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='user_create',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_movie_create_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='user_update',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_movie_update_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movieartistrole',
            name='user_create',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_movieartistrole_create_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movieartistrole',
            name='user_update',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_movieartistrole_update_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='user_create',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_moviegenre_create_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='user_update',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_moviegenre_update_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='user_create',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_role_create_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='user_update',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_role_update_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='type',
            name='user_create',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_type_create_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='type',
            name='user_update',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_type_update_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
