# Generated by Django 2.0.6 on 2018-07-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbsurfer', '0009_auto_20180613_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='index',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
