# Generated by Django 2.1 on 2018-09-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbsurfer', '0011_auto_20180816_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='last_index',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='last_update',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
