# Generated by Django 3.2.5 on 2021-07-04 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_create', models.DateTimeField(auto_now_add=True)),
                ('dh_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('obs', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtistRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_create', models.DateTimeField(auto_now_add=True)),
                ('dh_update', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdbsurfer_webapp.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_create', models.DateTimeField(auto_now_add=True)),
                ('dh_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('obs', models.CharField(blank=True, max_length=255, null=True)),
                ('user_create', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_genre_create_related', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_genre_update_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_create', models.DateTimeField(auto_now_add=True)),
                ('dh_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('obs', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('index', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('last_index', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('last_update', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('votes', models.PositiveIntegerField()),
                ('link', models.CharField(max_length=255)),
                ('minutes', models.PositiveSmallIntegerField(null=True)),
                ('metascore', models.PositiveSmallIntegerField(null=True)),
                ('watched', models.BooleanField(default=False)),
                ('watch', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-index', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_create', models.DateTimeField(auto_now_add=True)),
                ('dh_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('obs', models.CharField(blank=True, max_length=255, null=True)),
                ('user_create', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_type_create_related', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_type_update_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_create', models.DateTimeField(auto_now_add=True)),
                ('dh_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('obs', models.CharField(blank=True, max_length=255, null=True)),
                ('user_create', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_role_create_related', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_role_update_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_create', models.DateTimeField(auto_now_add=True)),
                ('dh_update', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveSmallIntegerField(null=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdbsurfer_webapp.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdbsurfer_webapp.movie')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdbsurfer_webapp.type')),
                ('user_create', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_moviegenre_create_related', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_moviegenre_update_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieArtistRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_create', models.DateTimeField(auto_now_add=True)),
                ('dh_update', models.DateTimeField(auto_now=True)),
                ('artistRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdbsurfer_webapp.artistrole')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdbsurfer_webapp.movie')),
                ('user_create', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_movieartistrole_create_related', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_movieartistrole_update_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='artists',
            field=models.ManyToManyField(through='imdbsurfer_webapp.MovieArtistRole', to='imdbsurfer_webapp.ArtistRole'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(through='imdbsurfer_webapp.MovieGenre', to='imdbsurfer_webapp.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='user_create',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_movie_create_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='user_update',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_movie_update_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_create', models.DateTimeField(auto_now_add=True)),
                ('dh_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('obs', models.CharField(blank=True, max_length=255, null=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('user_create', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_configuration_create_related', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_configuration_update_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='artistrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdbsurfer_webapp.role'),
        ),
        migrations.AddField(
            model_name='artistrole',
            name='user_create',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_artistrole_create_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artistrole',
            name='user_update',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_artistrole_update_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='role',
            field=models.ManyToManyField(through='imdbsurfer_webapp.ArtistRole', to='imdbsurfer_webapp.Role'),
        ),
        migrations.AddField(
            model_name='artist',
            name='user_create',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_artist_create_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='user_update',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='imdbsurfer_webapp_artist_update_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
